# Generated by Django 6.0.7 on 2026-07-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('architecture', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
