# Generated by Django 6.0.7 on 2026-07-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='network',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
