# Generated by Django 6.0.7 on 2026-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networking', '0002_network_managed_network_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='DnsRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdomain', models.CharField(max_length=255, unique=True)),
                ('target_instance', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
