# Generated by Django 6.0.7 on 2026-07-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_depositrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositrequest',
            name='sender_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
